shift to sample Buffer
      self = <buf real:False device:QCOM size:6504 dtype:dtypes.float offset:0>
      device = 'QCOM', size = 6504, dtype = dtypes.float, opaque = None
      options = None, initial_value = <pickle.PickleBuffer object at 0x7f21c7419d40>
      base = 1, offset = 0, preallocate = False

          def __init__(self, device:str, size:int, dtype:DType, opaque:Any=None, options:BufferSpec|None=None,
                       initial_value:bytes|pickle.PickleBuffer|None=None, base:Buffer|None=None, offset:int=0, preallocate=False):
            assert isinstance(dtype, DType)
            self.device, self.size, self.dtype, self.offset, self.allocated_views, self._base = Device.canonicalize(device), size, dtype, offset, 0, base
            self.options = options if options is not None else BufferSpec()
            self._storage:BufferStorage|None = None
            if base is None:
              assert offset == 0, "base buffers can't have offset"
              if opaque is not None: self.allocate(opaque)
              if initial_value is not None:
                self.allocate()
                if (host:=self.get_storage().host) is not None: host[:] = memoryview(initial_value).cast('B')
                else:
                  src = Buffer("PYTHON", self.nbytes, dtypes.uint8, opaque=memoryview(bytearray(initial_value)))
                  for offset in range(0, self.nbytes, 1 << 20):
                    size = min(self.nbytes - offset, 1 << 20)
                    self.view(size, dtypes.uint8, offset).ensure_allocated().copy_from(src.view(size, dtypes.uint8, offset).ensure_allocated())
                if isinstance(initial_value, pickle.PickleBuffer): initial_value.release()
            else:
      >       assert base._base is None, "base can't have a base"
                     ^^^^^^^^^^
      E       AttributeError: 'int' object has no attribute '_base'